pub_hdrs = hxx{**}

./: $pub_hdrs

# Install into the squish/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
hxx{*}:
{
  install         = include/squish/
  install.subdirs = true
}
